#!/usr/bin/env python3
"""Build the generated wiki pages and the app data file from fixture front matter.

Reads every wiki/fixtures/**/*.md (except _common pages), validates the YAML
front matter, and writes:
  wiki/index.md        - fixture list grouped by manufacturer
  wiki/comparison.md   - power / DMX / tools side by side
  wiki/passwords.md    - every known menu passcode in one place
  data/fixtures.json   - all front matter, for the future app

Usage: python3 tools/build_index.py           (rebuild)
       python3 tools/build_index.py --check   (validate only, non-zero exit on problems)
"""
import json
import math
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
FIXTURES = WIKI / "fixtures"
REQUIRED = ["title", "manufacturer", "model", "aliases", "type", "power", "dmx", "verification"]
HEADER = "<!-- Generated by tools/build_index.py from fixture front matter. Do not edit by hand. -->\n\n"


def read_front_matter(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError("no front matter")
    _, fm, _ = text.split("---", 2)
    data = yaml.safe_load(fm) or {}
    if not isinstance(data, dict):
        raise ValueError("front matter is not a mapping")
    return data


def load():
    fixtures, problems = [], []
    for path in sorted(FIXTURES.rglob("*.md")):
        if path.name.startswith("_"):
            continue
        rel = path.relative_to(WIKI).as_posix()
        try:
            fm = read_front_matter(path)
        except Exception as e:  # noqa: BLE001 - report every broken file, keep going
            problems.append(f"{rel}: {e}")
            continue
        missing = [k for k in REQUIRED if k not in fm]
        if missing:
            problems.append(f"{rel}: missing {', '.join(missing)}")
        fm["path"] = rel
        fixtures.append(fm)
    return fixtures, problems


def num(v):
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return v
    return None


def cell(v):
    if v is None or v == "" or v == []:
        return "—"
    if isinstance(v, list):
        return ", ".join(str(x) for x in v)
    return str(v).replace("|", "/").replace("\n", " ")


def per_circuit(power, volts):
    """Prefer the page's own computed value; fall back to floor(16 / amps)."""
    p = power or {}
    given = p.get(f"per_20a_{volts}v")
    if given is not None:
        return given
    amps = num(p.get(f"amps_{volts}v"))
    return math.floor(16 / amps) if amps else None


def link(f):
    return f"[{cell(f.get('title'))}]({f['path']})"


def build_index(fixtures):
    out = [HEADER, "# Fixture Index\n\n",
           "Search tip: in Obsidian or any Markdown app, search the fixture nickname (e.g. `outcast 2x`). "
           "Every page lists its aliases.\n\n",
           "Reference pages: [Power math](reference/power-math.md) · [DMX troubleshooting](reference/dmx-troubleshooting.md) · "
           "[Moving light troubleshooting](reference/moving-light-troubleshooting.md) · [Connectors & pinouts](reference/connectors-and-pinouts.md) · "
           "[Tool kit](reference/tool-kit.md) · [Passwords](passwords.md) · [Comparison table](comparison.md)\n\n"]
    by_maker = {}
    for f in fixtures:
        by_maker.setdefault(f.get("manufacturer") or "Unknown", []).append(f)
    for maker in sorted(by_maker):
        out.append(f"## {maker}\n\n| Fixture | Type | Also called | Verified |\n|---|---|---|---|\n")
        for f in sorted(by_maker[maker], key=lambda x: str(x.get("title"))):
            out.append(f"| {link(f)} | {cell(f.get('type'))} | {cell(f.get('aliases'))} | {cell(f.get('verification'))} |\n")
        out.append("\n")
    common = sorted(FIXTURES.rglob("_*.md"))
    if common:
        out.append("## Manufacturer common pages (menus, firmware, shared error codes)\n\n")
        for c in common:
            out.append(f"- [{c.parent.name} common]({c.relative_to(WIKI).as_posix()})\n")
    return "".join(out)


def build_comparison(fixtures):
    out = [HEADER, "# Comparison Table\n\n",
           "Per-circuit counts assume a 20 A circuit planned at 16 A, capped by the manufacturer link limit. "
           "See [Power math](reference/power-math.md). **Always confirm on the fixture page.**\n\n",
           "## Power\n\n| Fixture | Input | Conn in/out | A @120 | A @208 | Link @120 | Link @208 | **Per 20 A @120** | **Per 20 A @208** |\n"
           "|---|---|---|---|---|---|---|---|---|\n"]
    for f in sorted(fixtures, key=lambda x: str(x.get("title"))):
        p = f.get("power") or {}
        conn = f"{cell(p.get('connector_in'))} / {cell(p.get('connector_out'))}"
        out.append(f"| {link(f)} | {cell(p.get('input'))} | {conn} | {cell(p.get('amps_120v'))} | {cell(p.get('amps_208v'))} | "
                   f"{cell(p.get('link_max_120v'))} | {cell(p.get('link_max_208v'))} | **{cell(per_circuit(p, 120))}** | **{cell(per_circuit(p, 208))}** |\n")
    out.append("\n## DMX, weight & tools\n\n| Fixture | Type | DMX modes (ch) | Protocols | Weight lb | IP | Tools |\n|---|---|---|---|---|---|---|\n")
    for f in sorted(fixtures, key=lambda x: str(x.get("title"))):
        d = f.get("dmx") or {}
        modes = []
        for m in d.get("modes") or []:
            if isinstance(m, dict):
                modes.append(f"{m.get('name')} {m.get('channels')}")
            else:
                modes.append(str(m))
        out.append(f"| {link(f)} | {cell(f.get('type'))} | {cell(modes)} | {cell(d.get('protocols'))} | "
                   f"{cell(f.get('weight_lb'))} | {cell(f.get('ip_rating'))} | {cell(f.get('tools'))} |\n")
    return "".join(out)


def build_passwords(fixtures):
    out = [HEADER, "# Passwords & Menu Codes\n\n",
           "Default passcodes from manuals. **How to enter them is on each fixture page** (and in the maker's `_common` page). "
           "Rental shops sometimes change them.\n\n| Fixture | Passcode | Verified |\n|---|---|---|\n"]
    rows = [f for f in fixtures if f.get("menu_password") not in (None, "", "none")]
    for f in sorted(rows, key=lambda x: str(x.get("title"))):
        out.append(f"| {link(f)} | `{cell(f.get('menu_password'))}` | {cell(f.get('verification'))} |\n")
    none = [f for f in fixtures if f.get("menu_password") in (None, "", "none")]
    if none:
        out.append("\n## No passcode found yet\n\n")
        out.append(", ".join(link(f) for f in sorted(none, key=lambda x: str(x.get("title")))) + "\n")
    return "".join(out)


def main():
    fixtures, problems = load()
    for p in problems:
        print("PROBLEM:", p, file=sys.stderr)
    if "--check" in sys.argv:
        print(f"{len(fixtures)} fixtures, {len(problems)} problems")
        sys.exit(1 if problems else 0)
    (WIKI / "index.md").write_text(build_index(fixtures), encoding="utf-8")
    (WIKI / "comparison.md").write_text(build_comparison(fixtures), encoding="utf-8")
    (WIKI / "passwords.md").write_text(build_passwords(fixtures), encoding="utf-8")
    (ROOT / "data").mkdir(exist_ok=True)
    (ROOT / "data" / "fixtures.json").write_text(json.dumps(fixtures, indent=2, default=str, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Built index for {len(fixtures)} fixtures ({len(problems)} problems)")


if __name__ == "__main__":
    main()
